-- ============================================================================
-- V3__more_questions.sql : SQLD/SQLP 문제 시드 보강 (총 약 100문항)
--
-- 카테고리 ID (V2 에서 시드 완료, 1~7 고정):
--   1=데이터 모델링의 이해(SQLD)  2=데이터 모델과 SQL(SQLD)  3=SQL 기본(SQLD)
--   4=SQL 활용(SQLD)              5=관리 구문(SQLD)
--   6=SQL 수행 구조(SQLP)         7=고급 SQL 튜닝(SQLP)
--
-- 작성 규칙:
--   - 각 행: (category_id, content, option1~4, answer 1~4, explanation, difficulty)
--   - 한 카테고리당 한 INSERT 블록, EASY → MEDIUM → HARD 순서
--   - 따옴표는 PostgreSQL 표준 `''` 로 escape
--   - 출제 범위 기반 신규 작성 (기출 인용 X)
-- ============================================================================


-- ── SQLD : 데이터 모델링의 이해 (category_id = 1, 12문항) ────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (1,
     '데이터 모델링의 3대 요소에 해당하지 않는 것은?',
     'Things(엔터티)', 'Attributes(속성)', 'Relationships(관계)', 'Queries(쿼리)',
     4,
     '데이터 모델링 3대 요소는 엔터티·속성·관계이다. 쿼리는 모델링 결과를 사용하는 측면이다.',
     'EASY'),

    (1,
     '다음 중 데이터 모델링의 특성으로 거리가 먼 것은?',
     '추상화', '단순화', '명확화', '복잡화',
     4,
     '데이터 모델링의 3대 특성은 추상화·단순화·명확화이다.',
     'EASY'),

    (1,
     '속성(Attribute)에 대한 설명으로 가장 적절한 것은?',
     '엔터티가 갖는 의미 있는 정보 항목이다.',
     '관계의 차수를 나타낸다.',
     '인스턴스의 식별자 역할만 한다.',
     '항상 두 개 이상이어야 한다.',
     1,
     '속성은 엔터티 인스턴스의 상태를 기술하는 의미 있는 정보 단위이다.',
     'EASY'),

    (1,
     '관계의 표기에 사용되지 않는 항목은?',
     '관계명', '관계차수', '관계선택사양', '관계비용',
     4,
     '관계는 관계명·차수·선택사양으로 표기한다. ''관계비용''은 정의되어 있지 않다.',
     'EASY'),

    (1,
     '식별자 분류 기준에 해당하지 않는 것은?',
     '대표성(주/보조)', '스스로 생성 여부(본질/인조)', '데이터 타입(숫자/문자)', '단일성(단일/복합)',
     3,
     '식별자 분류 기준은 대표성·스스로 생성 여부·단일성·내부 외부이며, 데이터 타입은 분류 기준이 아니다.',
     'MEDIUM'),

    (1,
     '제1정규형(1NF)의 조건으로 옳은 것은?',
     '부분 함수 종속 제거', '이행 함수 종속 제거', '모든 속성이 원자값(atomic)', '결정자가 후보키여야 함',
     3,
     '1NF=원자값, 2NF=부분 종속 제거, 3NF=이행 종속 제거, BCNF=결정자가 후보키.',
     'MEDIUM'),

    (1,
     '반정규화(De-normalization)를 고려하는 주된 이유로 옳은 것은?',
     '무결성 강화', '저장 공간 절약', '조회 성능 향상', '보안 강화',
     3,
     '반정규화는 조인 비용을 줄여 조회 성능을 향상시키기 위해 의도적으로 중복을 허용한다.',
     'MEDIUM'),

    (1,
     '관계의 카디널리티(Cardinality)로 옳지 않은 것은?',
     '1:1', '1:M', 'M:N', '0:0',
     4,
     '카디널리티는 1:1, 1:M, M:N 세 가지이며 0:0 은 정의되지 않는다.',
     'MEDIUM'),

    (1,
     '본질식별자와 인조식별자에 대한 설명으로 옳은 것은?',
     '본질식별자는 시스템이 자동 생성한다.',
     '인조식별자는 본질식별자가 복합키여서 사용이 불편할 때 도입한다.',
     '인조식별자는 업무적 의미를 갖는다.',
     '본질식별자는 자주 변경되어도 무방하다.',
     2,
     '인조식별자(일련번호 등)는 본질식별자가 복합키이거나 변경 가능할 때 식별 안정성을 위해 도입된다.',
     'MEDIUM'),

    (1,
     '식별관계와 비식별관계에 대한 설명으로 옳은 것은?',
     '식별관계는 부모의 PK 가 자식의 PK 에 포함된다.',
     '식별관계는 표기상 점선이다.',
     '비식별관계는 부모 없이 자식이 존재할 수 없다.',
     '비식별관계의 표기는 항상 실선이다.',
     1,
     '식별관계는 부모 PK 가 자식 PK 의 일부가 되며 표기는 실선. 비식별관계는 부모 PK 가 자식의 일반 FK 로 점선 표기.',
     'MEDIUM'),

    (1,
     'BCNF(Boyce-Codd Normal Form)를 만족하기 위한 조건은?',
     '1NF 만 만족하면 자동으로 BCNF 이다.',
     '모든 결정자(determinant)가 후보키이어야 한다.',
     '이행 종속만 제거하면 충분하다.',
     '다치 종속을 제거해야 한다.',
     2,
     'BCNF 는 모든 결정자가 후보키여야 한다. 다치 종속 제거는 4NF.',
     'HARD'),

    (1,
     '슈퍼타입/서브타입 모델의 변환 방식 중 ''One Table(통합)'' 방식의 단점으로 가장 적절한 것은?',
     '서브타입별 분리 저장으로 조회 성능이 떨어진다.',
     'NULL 컬럼이 많아져 저장 효율과 가독성이 떨어진다.',
     '트랜잭션이 분산된다.',
     '무결성 보장이 불가능하다.',
     2,
     '통합 변환은 서브타입 고유 속성이 NULL 로 남아 저장 효율과 가독성이 나빠진다.',
     'HARD');


-- ── SQLD : 데이터 모델과 SQL (category_id = 2, 14문항) ──────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (2,
     '컬럼 값의 유효 범위를 보장하는 도메인 무결성 제약은?',
     'PRIMARY KEY', 'FOREIGN KEY', 'CHECK', 'UNIQUE',
     3,
     '도메인 무결성(컬럼 값 범위)은 CHECK 또는 데이터 타입으로 보장한다.',
     'EASY'),

    (2,
     '외래키(FK) 제약 조건에 대한 설명으로 옳은 것은?',
     '참조 무결성을 보장한다.',
     '항상 NOT NULL 이다.',
     '테이블당 하나만 가능하다.',
     '자기 자신을 참조할 수 없다.',
     1,
     'FK 는 참조 무결성을 보장하며, NULL 허용·복수 FK·자기 참조가 모두 가능하다.',
     'EASY'),

    (2,
     'ACID 의 ''A'' 가 의미하는 것은?',
     'Atomicity(원자성)', 'Availability(가용성)', 'Authorization(인가)', 'Auditing(감사)',
     1,
     'ACID = Atomicity, Consistency, Isolation, Durability.',
     'EASY'),

    (2,
     'ROLLBACK 의 효과로 옳은 것은?',
     '마지막 COMMIT(또는 SAVEPOINT) 이후의 변경을 취소한다.',
     '모든 테이블 데이터를 즉시 제거한다.',
     '데이터베이스를 재시작한다.',
     '인덱스를 재구성한다.',
     1,
     'ROLLBACK 은 트랜잭션 내 변경을 취소한다(마지막 COMMIT/SAVEPOINT 기준).',
     'EASY'),

    (2,
     'PRIMARY KEY 와 UNIQUE 제약의 차이로 옳은 것은?',
     'PK 는 NULL 허용, UNIQUE 는 불허',
     'PK 는 NULL 불허, UNIQUE 는 NULL 허용',
     '둘 다 NULL 을 허용한다',
     '둘 다 NULL 을 허용하지 않는다',
     2,
     'PK = NOT NULL + UNIQUE, UNIQUE 단독은 NULL 행을 허용하며 보통 다수의 NULL 도 허용된다.',
     'MEDIUM'),

    (2,
     'ON DELETE CASCADE 의 동작으로 옳은 것은?',
     '부모 삭제 시 자식 행도 함께 삭제',
     '부모 삭제 시 자식의 FK 를 NULL 처리',
     '부모 삭제 시 기본값으로 변경',
     '부모를 삭제할 수 없게 막음',
     1,
     'CASCADE 는 부모가 삭제될 때 자식 행을 함께 삭제하는 옵션이다.',
     'MEDIUM'),

    (2,
     'ON DELETE SET NULL 동작 후 자식 FK 컬럼 값은?',
     '0', '빈 문자열', 'NULL', '부모의 기본값',
     3,
     'SET NULL 은 부모 삭제 시 자식 FK 를 NULL 로 변경한다. FK 가 NOT NULL 이면 사용 불가.',
     'MEDIUM'),

    (2,
     'SAVEPOINT 의 용도로 옳은 것은?',
     '트랜잭션 내부의 부분 롤백 지점 표시',
     '데이터베이스 자동 백업 시점',
     '인덱스 통계 갱신 시점',
     '트랜잭션 자동 종료 지점',
     1,
     'SAVEPOINT 는 트랜잭션 내부에 지점을 만들어 그 지점까지 ROLLBACK 할 수 있게 한다.',
     'MEDIUM'),

    (2,
     'ALTER TABLE 같은 DDL 수행 시 일반적인 RDBMS 동작은?',
     '메모리에서만 변경, 디스크에는 반영 안 됨',
     '자동 커밋이 발생해 이전 미커밋 변경도 함께 확정된다',
     '데이터를 임시 테이블로 복제한 뒤 적용',
     '항상 다른 트랜잭션을 무한 대기시킨다',
     2,
     'Oracle 등 대다수 RDBMS 에서 DDL 은 자동 커밋이다(MySQL 도 동일). PostgreSQL 은 DDL 도 트랜잭션 안에서 가능한 예외.',
     'MEDIUM'),

    (2,
     'ERD 에서 1:M 관계를 테이블로 변환하는 일반적 방법은?',
     'M 쪽 테이블에 FK 추가',
     '1 쪽 테이블에 FK 추가',
     '별도 연결 테이블 생성',
     '양쪽 모두 FK 추가',
     1,
     '1:M 은 M 쪽에 1 쪽의 PK 를 FK 로 둔다. M:N 은 연결 테이블 필요.',
     'MEDIUM'),

    (2,
     'M:N 관계를 테이블로 변환할 때 일반적으로 필요한 것은?',
     '연결 테이블 생성',
     '양쪽에 동일한 PK 부여',
     '양쪽에 동일한 FK 추가',
     'M 쪽에 추가 PK',
     1,
     'M:N 은 두 PK 를 FK 로 갖는 연결 테이블을 만들어 두 개의 1:M 관계로 분해한다.',
     'MEDIUM'),

    (2,
     '트랜잭션 격리 수준 중 가장 엄격한 단계는?',
     'READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE',
     4,
     '격리수준 4단계 중 SERIALIZABLE 이 가장 엄격하며 동시성은 낮고 일관성은 높다.',
     'MEDIUM'),

    (2,
     'NULL 이 포함된 컬럼에 UNIQUE 제약이 걸려 있을 때 일반적인 RDBMS 동작은?',
     'NULL 한 행만 허용',
     'NULL 다수 행 허용',
     'NULL 행 자체를 거부',
     'UNIQUE 제약과 무관하게 항상 에러',
     2,
     '표준 SQL 은 NULL 끼리 동일하지 않다고 보아 UNIQUE 컬럼에 다수의 NULL 행을 허용한다.',
     'HARD'),

    (2,
     'FK 가 있는 자식 행이 존재할 때 부모 행을 삭제하려는 경우, ON DELETE 옵션을 명시하지 않았을 때의 기본 동작은?',
     '자동으로 자식도 삭제',
     '자식 FK 를 NULL 로 변경',
     '삭제 거부(RESTRICT/NO ACTION)',
     '트랜잭션 전체 ROLLBACK',
     3,
     '기본 동작은 RESTRICT/NO ACTION 으로, 참조하는 자식이 있으면 부모 삭제를 거부한다.',
     'HARD');


-- ── SQLD : SQL 기본 (category_id = 3, 16문항) ───────────────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (3,
     'SELECT 문의 논리적 실행 순서로 옳은 것은?',
     'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY',
     'SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY',
     'FROM → SELECT → WHERE → GROUP BY → ORDER BY → HAVING',
     'SELECT → WHERE → FROM → GROUP BY → HAVING → ORDER BY',
     1,
     '논리적 처리 순서: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY.',
     'EASY'),

    (3,
     'DISTINCT 의 역할로 옳은 것은?',
     '중복 행 제거', '정렬', '그룹화', 'NULL 제거',
     1,
     'DISTINCT 는 결과 집합에서 중복 행을 제거한다.',
     'EASY'),

    (3,
     'WHERE col IN (1, 2, 3) 과 의미가 같은 표현은?',
     'col = 1 AND col = 2 AND col = 3',
     'col = 1 OR col = 2 OR col = 3',
     'col BETWEEN 1 AND 3',
     'col >= 1 AND col <= 3',
     2,
     'IN 은 OR 조건의 축약. BETWEEN 은 연속 범위라 정수 1~3 에 한해서만 우연히 동등.',
     'EASY'),

    (3,
     '다음 중 집계함수가 아닌 것은?',
     'SUM', 'AVG', 'ROUND', 'COUNT',
     3,
     'ROUND 는 스칼라(숫자) 함수. 집계함수는 SUM, AVG, COUNT, MAX, MIN 등.',
     'EASY'),

    (3,
     '컬럼이 NULL 인지 확인하는 올바른 표현은?',
     'col = NULL', 'col == NULL', 'col IS NULL', 'col <=> NULL',
     3,
     'NULL 은 = 로 비교할 수 없으며 IS NULL / IS NOT NULL 을 사용해야 한다.',
     'EASY'),

    (3,
     'GROUP BY 결과를 필터링할 때 사용하는 절은?',
     'WHERE', 'HAVING', 'FILTER', 'FETCH',
     2,
     '그룹 단위 필터는 HAVING, 행 단위 필터는 WHERE.',
     'MEDIUM'),

    (3,
     'COALESCE(a, b, c) 의 동작은?',
     '가장 큰 값', '가장 작은 값', '앞에서부터 NULL 이 아닌 첫 값', '평균',
     3,
     'COALESCE 는 인자 중 NULL 이 아닌 첫 값을 반환한다. NVL(a, b) 는 Oracle 2-인자 형태.',
     'MEDIUM'),

    (3,
     'CASE WHEN ... THEN ... END 에서 ELSE 가 생략되고 어떤 WHEN 도 매치되지 않을 때 결과는?',
     '0', '빈 문자열', 'NULL', '에러',
     3,
     'ELSE 생략 시 매치되는 WHEN 이 없으면 NULL 을 반환한다.',
     'MEDIUM'),

    (3,
     'LIKE 패턴에서 정확히 한 문자를 의미하는 와일드카드는?',
     '%', '_', '*', '?',
     2,
     'SQL LIKE: % = 0개 이상 문자, _ = 정확히 한 문자.',
     'MEDIUM'),

    (3,
     'INNER JOIN 의 ON 절 조건이 결과에 미치는 영향으로 옳은 것은?',
     '매치되지 않는 행을 제외해 결과 행 수를 결정',
     '결과의 정렬 순서를 결정',
     '그룹화 기준을 결정',
     '결과 컬럼 목록을 결정',
     1,
     'INNER JOIN 의 ON 은 매치 조건이며, 매치되지 않는 행은 결과에서 제외된다.',
     'MEDIUM'),

    (3,
     'A LEFT OUTER JOIN B ON ... 의 결과로 옳은 것은?',
     'A 와 B 의 교집합만 반환',
     'A 의 모든 행 + 매치 B(미매치 시 NULL)',
     'B 의 모든 행 + 매치 A',
     'A 와 B 의 합집합',
     2,
     'LEFT OUTER JOIN 은 왼쪽의 모든 행을 보존하고, 매치되는 오른쪽이 없으면 NULL 로 채운다.',
     'MEDIUM'),

    (3,
     'CROSS JOIN 의 결과 행 수는?',
     'A 행수 + B 행수', 'A 행수 × B 행수', 'A 행수', 'min(A, B)',
     2,
     'CROSS JOIN 은 카르테시안 곱으로 두 테이블의 행 수를 곱한다.',
     'MEDIUM'),

    (3,
     'NVL(col, 0) 과 동등한 ANSI 표준 SQL 표현은?',
     'COALESCE(col, 0)', 'ISNULL(col, 0)', 'IFNULL(col, 0)', 'DEFAULT(col, 0)',
     1,
     'COALESCE 가 ANSI 표준. ISNULL 은 SQL Server, IFNULL 은 MySQL 의 방언.',
     'MEDIUM'),

    (3,
     'ORDER BY 1 DESC 의 의미는?',
     '상수 1 을 기준으로 정렬',
     'SELECT 리스트의 첫 번째 컬럼을 내림차순 정렬',
     '1 행만 반환',
     '인덱스 1번을 사용',
     2,
     'ORDER BY 의 숫자는 SELECT 리스트의 N 번째 컬럼을 가리킨다.',
     'MEDIUM'),

    (3,
     'COUNT(*) 와 COUNT(col) 의 차이로 옳은 것은?',
     '동일하다',
     'COUNT(*) 는 NULL 도 포함하고 COUNT(col) 은 col 이 NULL 이 아닌 행만 센다',
     'COUNT(col) 이 항상 더 빠르다',
     'COUNT(*) 는 PK 가 있어야 동작한다',
     2,
     'COUNT(*) = 전체 행, COUNT(col) = col 이 NULL 이 아닌 행 수.',
     'HARD'),

    (3,
     'NULL 의 정렬 위치에 대한 설명으로 옳은 것은?',
     'NULL 은 항상 최솟값으로 정렬된다',
     'NULL 은 항상 최댓값으로 정렬된다',
     'DBMS 마다 다르며 NULLS FIRST/LAST 로 명시 가능하다',
     'NULL 은 정렬에서 자동으로 제외된다',
     3,
     'NULL 정렬 기본 위치는 DBMS 마다 다르며(Oracle ASC=마지막, MySQL=처음 등), NULLS FIRST/LAST 로 명시할 수 있다.',
     'HARD');


-- ── SQLD : SQL 활용 (category_id = 4, 16문항) ──────────────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (4,
     'UNION 과 UNION ALL 의 차이로 옳은 것은?',
     'UNION 은 중복 제거, UNION ALL 은 중복 포함',
     'UNION 이 더 빠르다',
     'UNION ALL 은 정렬을 강제한다',
     'UNION 은 첫 컬럼만 합친다',
     1,
     'UNION 은 중복 행을 제거(추가 정렬/해시 비용), UNION ALL 은 그대로 합쳐 더 빠르다.',
     'EASY'),

    (4,
     'ROW_NUMBER() OVER (ORDER BY x) 의 결과 특성은?',
     '동순위에 같은 번호 부여',
     '동순위에도 1,2,3 처럼 고유 번호 부여',
     'NULL 행을 자동 제외',
     '항상 1만 반환',
     2,
     'ROW_NUMBER 는 동순위라도 1, 2, 3 식으로 고유 번호를 부여한다.',
     'EASY'),

    (4,
     'EXISTS 와 IN 의 차이로 옳은 것은?',
     '동일하다',
     'EXISTS 는 매치 여부만 확인하므로 NULL 영향이 적다',
     'IN 이 항상 더 빠르다',
     'EXISTS 는 서브쿼리 결과 전체를 메모리에 적재한다',
     2,
     'EXISTS 는 존재 여부만 보므로 NULL 영향이 적고 대량 서브쿼리에서 효율적인 경우가 많다.',
     'EASY'),

    (4,
     'INTERSECT 의 결과로 옳은 것은?',
     '합집합', '차집합', '교집합', '카르테시안 곱',
     3,
     'INTERSECT 는 두 집합의 교집합을 반환한다.',
     'EASY'),

    (4,
     'RANK() 와 DENSE_RANK() 의 차이로 옳은 것은?',
     'RANK 는 동순위 다음을 건너뛰지 않고, DENSE_RANK 는 건너뛴다',
     'RANK 는 동순위 다음 순위를 건너뛰고, DENSE_RANK 는 건너뛰지 않는다',
     '동일하다',
     'DENSE_RANK 는 NULL 을 항상 1순위로 둔다',
     2,
     '두 명이 1등이면 RANK 는 다음을 3등, DENSE_RANK 는 2등으로 부여한다.',
     'MEDIUM'),

    (4,
     'GROUP BY ROLLUP(a, b) 의 결과 그룹으로 옳은 것은?',
     '(a, b), (a), (b), () 모두',
     '(a, b), (a), () 의 소계',
     '(a, b), (b), () 의 소계',
     '(a, b) 한 그룹만',
     2,
     'ROLLUP(a, b) 은 왼쪽부터 차례로 줄여 (a, b), (a), () 의 소계를 제공한다.',
     'MEDIUM'),

    (4,
     'GROUP BY CUBE(a, b) 의 결과 그룹은?',
     '(a, b), (a), () 의 소계',
     '(a, b), (b), () 의 소계',
     '(a, b), (a), (b), () 모두',
     '(a, b) 한 그룹만',
     3,
     'CUBE 는 모든 가능한 부분집합 그룹의 소계를 제공한다.',
     'MEDIUM'),

    (4,
     '계층 질의의 시작점을 지정하는 절은?',
     'START WITH', 'BEGIN', 'ROOT', 'LEVEL',
     1,
     'Oracle 계층 질의는 START WITH 로 루트를 지정하고 CONNECT BY 로 부모-자식 관계를 명시한다.',
     'MEDIUM'),

    (4,
     '윈도우 함수에서 PARTITION BY 절의 역할은?',
     '결과를 그룹별로 윈도우 함수 적용 단위 분할',
     '결과 행을 정렬',
     'NULL 제거',
     '인덱스 분할',
     1,
     'PARTITION BY 는 윈도우 함수의 적용 단위를 분할(GROUP BY 와 달리 행 수는 줄이지 않음).',
     'MEDIUM'),

    (4,
     'LAG(col, 1) OVER (ORDER BY x) 의 의미는?',
     '다음 행의 col 값', '이전 행의 col 값', '최대값', '최소값',
     2,
     'LAG 는 윈도우 내 이전 행 값(기본 1행 전). LEAD 는 다음 행.',
     'MEDIUM'),

    (4,
     'WITH 절(공통 테이블 표현식, CTE) 의 장점으로 가장 적절한 것은?',
     '반복되는 서브쿼리의 가독성·재사용성 향상',
     '인덱스 자동 생성',
     '트랜잭션 격리',
     '디스크 정렬 회피',
     1,
     'WITH 절은 동일 서브쿼리 반복 작성을 피해 가독성과 재사용성을 높인다.',
     'MEDIUM'),

    (4,
     'MINUS(또는 EXCEPT) 연산자의 결과로 옳은 것은?',
     'A 와 B 의 교집합',
     'A 에는 있고 B 에 없는 행',
     'A 와 B 의 합집합',
     'B 에는 있고 A 에 없는 행',
     2,
     'A MINUS B = A 에는 있고 B 에는 없는 행. ANSI 표준은 EXCEPT.',
     'MEDIUM'),

    (4,
     'SELECT 절에서 사용되는 스칼라 서브쿼리의 제약으로 옳은 것은?',
     '두 컬럼 이상도 반환 가능',
     '한 행, 한 컬럼만 반환',
     '여러 행을 반환할 수 있다',
     '다른 테이블 참조 불가',
     2,
     '스칼라 서브쿼리는 1행 1컬럼만 반환해야 한다.',
     'MEDIUM'),

    (4,
     'GROUPING SETS((a, b), (a), ()) 와 동등한 표현은?',
     'CUBE(a, b)',
     'ROLLUP(a, b)',
     'GROUP BY a, b',
     'GROUP BY a UNION ALL GROUP BY b',
     2,
     'ROLLUP(a, b) = GROUPING SETS((a, b), (a), ()) 이다.',
     'HARD'),

    (4,
     '상관 서브쿼리(Correlated Subquery)의 실행 방식 특성은?',
     '한 번만 실행된다',
     '외부 쿼리의 각 행마다 평가될 수 있다',
     '절대로 실행되지 않는다',
     '항상 인덱스를 사용한다',
     2,
     '상관 서브쿼리는 외부 쿼리의 각 행을 참조하므로 외부 행 수만큼 평가될 수 있다(옵티마이저가 조인으로 변환할 수도 있음).',
     'HARD'),

    (4,
     'NTILE(4) OVER (ORDER BY x) 의 동작으로 옳은 것은?',
     'x 의 값을 4 배로 곱한다',
     '정렬 결과를 4 개 버킷으로 균등 분할해 1~4 번호 부여',
     '상위 4 개 행만 반환',
     '4 행 단위로 그룹화',
     2,
     'NTILE(n) 은 정렬 결과를 n 개의 버킷으로 균등 분할해 각 행에 버킷 번호를 부여한다.',
     'HARD');


-- ── SQLD : 관리 구문 (category_id = 5, 12문항) ──────────────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (5,
     'DCL 에 해당하는 명령은?',
     'CREATE', 'UPDATE', 'GRANT', 'COMMIT',
     3,
     'DCL = GRANT, REVOKE. CREATE=DDL, UPDATE=DML, COMMIT=TCL.',
     'EASY'),

    (5,
     'DML 에 해당하는 명령은?',
     'CREATE', 'DROP', 'ALTER', 'UPDATE',
     4,
     'DML = INSERT, UPDATE, DELETE, MERGE. 나머지는 DDL.',
     'EASY'),

    (5,
     '일반 VIEW 에 대한 설명으로 옳은 것은?',
     '물리적 저장 공간을 갖는다',
     '가상 테이블이며 매번 정의된 SELECT 가 실행된다',
     '인덱스를 만들 수 없다',
     'UPDATE 가 절대 불가능하다',
     2,
     '일반 뷰는 가상 테이블이고 호출 시마다 정의 SELECT 가 실행된다. Materialized View 는 저장형.',
     'EASY'),

    (5,
     'MERGE 문의 용도로 가장 적절한 것은?',
     '두 테이블의 조인 결과 반환',
     '조건에 따라 INSERT 또는 UPDATE 수행(UPSERT)',
     '데이터 일괄 삭제',
     '인덱스 병합',
     2,
     'MERGE 는 매치 시 UPDATE, 미매치 시 INSERT 를 한 문장으로 처리한다.',
     'EASY'),

    (5,
     'GRANT SELECT, INSERT ON tbl TO user1; 의 효과로 옳은 것은?',
     'user1 에게 tbl 의 SELECT/INSERT 권한 부여',
     'user1 에게 모든 권한 부여',
     'user1 의 권한을 모두 회수',
     'tbl 의 소유자를 user1 로 변경',
     1,
     'GRANT 는 지정 권한을 지정 사용자/롤에 부여한다.',
     'MEDIUM'),

    (5,
     'ROLE 의 장점으로 옳은 것은?',
     '권한 집합을 묶어 사용자 그룹별 일괄 부여/회수',
     '권한 자체를 더 강하게 만듦',
     '인덱스 효율을 향상',
     '백업을 자동화',
     1,
     'ROLE 은 권한 집합. 사용자에게 ROLE 을 부여해 권한 관리를 단순화한다.',
     'MEDIUM'),

    (5,
     'SEQUENCE 의 NEXTVAL 을 같은 트랜잭션에서 연속 호출했을 때의 동작은?',
     '같은 값 반환', '다음 값 반환', '에러', 'NULL',
     2,
     'NEXTVAL 은 호출 때마다 시퀀스를 증가시킨 다음 값을 반환한다. ROLLBACK 해도 시퀀스는 복구되지 않음.',
     'MEDIUM'),

    (5,
     'CREATE INDEX 의 일반적 영향으로 옳은 것은?',
     'SELECT 는 빨라질 수 있으나 INSERT/UPDATE/DELETE 는 느려질 수 있다',
     '모든 DML 이 함께 빨라진다',
     '디스크 사용량이 줄어든다',
     '트랜잭션 격리수준이 올라간다',
     1,
     '인덱스는 조회 성능↑, 변경 시 인덱스 유지 비용 추가로 DML 비용↑.',
     'MEDIUM'),

    (5,
     'ALTER TABLE 로 수행할 수 없는 작업은?',
     '컬럼 추가',
     '컬럼 데이터 타입 변경',
     '컬럼 삭제',
     '테이블에 들어 있는 데이터를 한 번에 변환 저장',
     4,
     'ALTER 는 정의 변경. 데이터 일괄 변환은 UPDATE/INSERT INTO ... SELECT 등 DML 로 처리한다.',
     'MEDIUM'),

    (5,
     'DROP TABLE 과 TRUNCATE TABLE 의 차이로 옳은 것은?',
     '둘 다 정의를 제거한다',
     'DROP 은 정의와 데이터 모두, TRUNCATE 는 데이터만 제거(정의 유지)',
     'TRUNCATE 는 항상 더 안전하다',
     'DROP 은 자동 ROLLBACK 된다',
     2,
     'DROP = 정의 + 데이터 모두 제거, TRUNCATE = 데이터만 빠르게 제거하고 정의 유지.',
     'MEDIUM'),

    (5,
     'INSERT INTO ... SELECT ... 구문의 특징으로 옳은 것은?',
     '한 번에 한 행만 입력 가능',
     'SELECT 결과 전체를 한 번에 INSERT 가능',
     'DDL 이라 자동 커밋된다',
     '조건절을 사용할 수 없다',
     2,
     'INSERT ... SELECT 는 SELECT 결과를 그대로 대량 입력하는 DML.',
     'HARD'),

    (5,
     'WITH GRANT OPTION 으로 전파된 권한을 회수(REVOKE)할 때 일반적인 동작은?',
     '회수 후에도 다른 사용자는 권한 유지',
     '회수 시 권한을 다시 받은 사용자도 함께 회수(cascade)',
     'REVOKE 자체가 거부됨',
     '자동 ROLLBACK',
     2,
     'WITH GRANT OPTION 으로 전파된 권한은 회수 시 CASCADE 로 함께 회수되는 것이 일반적이다.',
     'HARD');


-- ── SQLP : SQL 수행 구조 (category_id = 6, 15문항) ─────────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (6,
     'SELECT 의 SQL 처리 단계 순서로 옳은 것은?',
     '파싱 → 실행 → 인출',
     '실행 → 파싱 → 인출',
     '인출 → 파싱 → 실행',
     '파싱 → 인출 → 실행',
     1,
     'SELECT 의 처리 흐름은 Parse → Execute → Fetch 순이다.',
     'EASY'),

    (6,
     'CBO 와 RBO 의 가장 큰 차이는?',
     'CBO 는 통계 기반, RBO 는 규칙 기반',
     'CBO 는 항상 더 느리다',
     'RBO 는 통계를 강제로 요구한다',
     '동일하다',
     1,
     'CBO=Cost-Based(통계 기반), RBO=Rule-Based(고정 규칙). 현대 RDBMS 는 CBO 가 표준.',
     'EASY'),

    (6,
     'Hard Parse 와 Soft Parse 의 차이로 옳은 것은?',
     'Hard 는 캐시에서 재사용, Soft 는 새로 파싱',
     'Soft 는 캐시에서 재사용, Hard 는 새로 파싱',
     '동일하다',
     'Soft 는 DDL 에만 적용',
     2,
     '동일 SQL 이 라이브러리 캐시에 있으면 Soft(재사용), 없으면 Hard(전체 파싱). Hard 가 훨씬 비싸다.',
     'MEDIUM'),

    (6,
     '바인드 변수 사용의 효과로 가장 적절한 것은?',
     'Hard Parse 감소 및 라이브러리 캐시 효율 향상',
     '실행 속도가 항상 느려진다',
     'SQL Injection 위험 증가',
     '옵티마이저 무시',
     1,
     '바인드 변수는 동일한 SQL 형태를 만들어 캐시 재사용을 가능케 하고, SQL Injection 도 방어한다.',
     'MEDIUM'),

    (6,
     '라이브러리 캐시(Library Cache)의 주된 저장 대상은?',
     '데이터 블록',
     '파싱된 SQL 과 실행계획',
     '트랜잭션 로그',
     '인덱스 파일',
     2,
     '라이브러리 캐시는 파싱된 SQL 과 실행계획을 보관해 재사용성을 높인다.',
     'MEDIUM'),

    (6,
     '실행 계획에서 ''Cost'' 가 의미하는 것은?',
     '옵티마이저가 추정한 상대적 비용',
     '실제 CPU 시간(μs)',
     '디스크 용량',
     '트랜잭션 ID',
     1,
     'Cost 는 통계 기반의 상대 비용 추정치이며 절대 시간이 아니다.',
     'MEDIUM'),

    (6,
     '동일 SQL 이 갑자기 느려졌을 때 가능성이 낮은 원인은?',
     '통계 갱신으로 실행 계획이 바뀜',
     '바인드 변수 피킹의 영향',
     '데이터 분포의 큰 변화',
     '하드웨어 CPU 클럭이 일반적으로 떨어졌기 때문',
     4,
     '주된 원인은 계획 변경(통계/분포/피킹). 하드웨어 클럭 변화는 흔치 않다.',
     'MEDIUM'),

    (6,
     '옵티마이저가 실행계획 결정에 사용하지 않는 정보는?',
     '테이블 통계(행수·평균 행 길이)',
     '인덱스 통계(고유값 수·NDV)',
     '시스템 통계(I/O·CPU 속도)',
     '트랜잭션 ID',
     4,
     '실행 계획은 통계 기반. 트랜잭션 ID 는 결정에 사용되지 않는다.',
     'MEDIUM'),

    (6,
     '실행 계획의 ''Cardinality(Rows)'' 가 의미하는 것은?',
     '해당 단계의 예상 행 수',
     '예상 비용',
     '사용된 메모리',
     '정렬 키',
     1,
     'Cardinality 는 해당 연산이 처리할 예상 행 수. 추정 오차는 비용 오차로 이어진다.',
     'MEDIUM'),

    (6,
     'SQL 트레이스의 주된 용도는?',
     'SQL 의 실제 수행 시간·I/O 등 실측 수집',
     '인덱스 자동 생성',
     '트랜잭션 격리 변경',
     '권한 부여',
     1,
     '트레이스는 실측 통계(논리/물리 I/O, 시간, 행수)를 수집해 실측 기반 튜닝을 가능케 한다.',
     'MEDIUM'),

    (6,
     '바인드 변수 피킹(Bind Peeking)의 부작용으로 옳은 것은?',
     '모든 SQL 이 항상 빨라진다',
     '첫 실행 바인드 값에 맞춰진 계획이 이후 다른 값에 비효율적일 수 있다',
     'Soft Parse 가 비활성화된다',
     '옵티마이저가 RBO 로 전환된다',
     2,
     '피킹은 첫 바인드 값으로 계획을 결정해 캐시. 데이터 분포가 다른 값에는 부적합할 수 있다(Adaptive Cursor Sharing 으로 보완).',
     'HARD'),

    (6,
     '동일한 SQL 텍스트가 라이브러리 캐시에서 공유되지 않는 흔한 사유는?',
     '공백·대소문자 등 텍스트 불일치',
     '같은 옵티마이저 힌트 사용',
     '바인드 변수 사용',
     'Cost 동일',
     1,
     '라이브러리 캐시는 텍스트 일치를 요구해 공백·대소문자 차이가 있으면 별개의 SQL 로 취급된다.',
     'HARD'),

    (6,
     'CURSOR_SHARING 을 FORCE 로 설정할 때의 부작용으로 옳은 것은?',
     '리터럴이 바인드로 자동 치환되어 실행계획이 부정확해질 수 있다',
     'Hard Parse 가 증가한다',
     'SQL Injection 이 강화된다',
     '항상 빨라진다',
     1,
     '리터럴 강제 치환은 캐시 재사용엔 좋지만 데이터 분포 차이로 계획이 부적합해질 수 있다.',
     'HARD'),

    (6,
     'AUTOTRACE 의 ''consistent gets'' 항목의 의미는?',
     '일관성 모드의 논리적 블록 읽기 수',
     '물리 디스크 I/O 수',
     '정렬 사용 횟수',
     '트랜잭션 수',
     1,
     'consistent gets 는 일관성 읽기의 논리 I/O 횟수로, 튜닝 시 핵심 지표이다.',
     'HARD'),

    (6,
     'Adaptive Plan(적응형 계획) 의 주된 의의는?',
     '실행 중 실측치를 보고 계획을 보정',
     '통계 없이 동작',
     '항상 NL 조인을 사용',
     '옵티마이저 비활성화',
     1,
     '적응형 계획은 실행 중 카디널리티가 추정과 크게 다르면 NL → Hash 등으로 전환해 실측 기반 보정한다.',
     'HARD');


-- ── SQLP : 고급 SQL 튜닝 (category_id = 7, 15문항) ─────────────────────────
INSERT INTO questions (category_id, content, option1, option2, option3, option4, answer, explanation, difficulty) VALUES
    (7,
     'NL(Nested Loop) 조인이 가장 적합한 상황은?',
     '양쪽 모두 매우 크고 정렬되어 있을 때',
     '한쪽이 작고 다른 쪽의 조인 키에 효율적인 인덱스가 있을 때',
     '양쪽 모두 풀스캔이 필요할 때',
     '조인 키가 없을 때',
     2,
     'NL 은 외부(드라이빙) 결과 행마다 내부 인덱스로 점근. 외부가 작고 내부 인덱스가 좋을 때 강함.',
     'EASY'),

    (7,
     'Hash Join 이 일반적으로 효율적인 상황은?',
     '한쪽이 매우 작고 인덱스가 없을 때',
     '대량 데이터의 동등(=) 조인',
     '부등호(<, >) 조인',
     'NL 보다 항상 빠름',
     2,
     'Hash Join 은 한쪽으로 해시 테이블을 만들어 다른 쪽을 탐색. 대량 동등조인에 강하다(부등호 조인 불가).',
     'MEDIUM'),

    (7,
     'Sort-Merge Join 의 특징으로 옳은 것은?',
     '양쪽 입력을 조인 키로 정렬 후 병합',
     '한쪽만 정렬',
     '정렬 없이 처리',
     '항상 NL 보다 느림',
     1,
     '양쪽을 정렬 후 병합하므로, 이미 정렬된 입력이나 부등호 조인에서 유용하다.',
     'MEDIUM'),

    (7,
     'Clustering Factor 가 높다는 것의 의미는?',
     '인덱스 순서와 테이블 행 순서가 일치한다',
     '인덱스 키 인접 행이 서로 다른 블록에 흩어져 있다',
     '인덱스가 손상되었다',
     '인덱스가 없다',
     2,
     'Clustering Factor 가 높을수록 인덱스 키로 인접한 행들이 흩어져 있어 Range Scan 비용이 증가한다.',
     'MEDIUM'),

    (7,
     'Index Skip Scan 이 효과적인 상황은?',
     '결합 인덱스의 선두 컬럼 NDV(고유값 수)가 매우 낮을 때',
     '단일 컬럼 인덱스일 때',
     '풀스캔이 빠를 때',
     '항상 Range Scan 보다 빠름',
     1,
     '선두 컬럼 카디널리티가 낮으면 그 값별 부분 트리를 스킵하며 후행 컬럼 조건으로 탐색이 가능하다.',
     'MEDIUM'),

    (7,
     'RANGE 파티션이 가장 적합한 경우는?',
     '날짜 등 범위로 데이터가 자연스럽게 구분될 때',
     '균등 분포가 필요할 때',
     '키가 전혀 없는 테이블',
     '파티션 키가 자주 변경될 때',
     1,
     'RANGE 파티션은 시간·범위로 명확히 구분되는 경우에 적합. 균등 분포는 HASH.',
     'MEDIUM'),

    (7,
     '결합 인덱스 (a, b) 가 있을 때 가장 효율적으로 사용되는 조건은?',
     'WHERE b = ?',
     'WHERE a = ? 또는 WHERE a = ? AND b = ?',
     'WHERE b > ?',
     'WHERE a IS NULL',
     2,
     '결합 인덱스는 선두 컬럼에 = 또는 범위 조건이 있어야 효율. b 단독 조건은 Skip Scan 외에는 비효율.',
     'MEDIUM'),

    (7,
     '옵티마이저 힌트 /*+ INDEX(t idx) */ 의 효과는?',
     '강제 풀스캔',
     '지정 인덱스 사용 권장',
     '예외 없이 인덱스 사용 강제',
     '인덱스 삭제',
     2,
     '힌트는 일반적으로 권고. 데이터 타입 불일치 등 사용 불가 상황에서는 무시될 수 있다.',
     'MEDIUM'),

    (7,
     '서브쿼리 언네스팅(Unnesting)의 효과로 옳은 것은?',
     '서브쿼리를 조인으로 변환해 옵티마이저 선택지를 넓힘',
     '서브쿼리를 강제로 분리',
     '인덱스 자동 생성',
     '정렬 강제',
     1,
     '언네스팅은 EXISTS/IN 같은 서브쿼리를 조인으로 변환해 Hash/Sort-Merge 등 다양한 조인 방법을 가능케 한다.',
     'HARD'),

    (7,
     'Index Fast Full Scan 의 특징으로 옳은 것은?',
     '인덱스 정렬 순서로 읽는다',
     '인덱스 블록을 멀티블록 I/O 로 빠르게 읽되 정렬 순서를 보장하지 않는다',
     '항상 Range Scan 보다 느리다',
     'NULL 만 있는 행도 함께 읽는다',
     2,
     'Fast Full Scan 은 인덱스 전 블록을 멀티블록 I/O 로 읽되 정렬 순서 보장은 없음. NULL 만 있는 행은 인덱스에 들어가지 않음.',
     'HARD'),

    (7,
     'Bitmap Index 가 효과적인 컬럼 특성은?',
     'NDV(카디널리티) 가 낮은 컬럼',
     '고유 값이 매우 많은 컬럼',
     '자주 갱신되는 OLTP 컬럼',
     'NULL 만 있는 컬럼',
     1,
     'Bitmap 은 성별·플래그 등 NDV 가 낮은 컬럼에 강함. 갱신 잦으면 lock 비용이 커진다.',
     'HARD'),

    (7,
     '뷰 머지(View Merging) 가 일반적으로 발생하지 않는 경우는?',
     '집계·DISTINCT·ROWNUM·계층질의·UNION 등이 뷰에 포함될 때',
     '뷰가 단순 SELECT 일 때',
     '뷰가 인라인일 때',
     '뷰의 모든 컬럼이 사용될 때',
     1,
     '집계·DISTINCT·ROWNUM·계층질의·UNION 등은 뷰 머지를 방해해 별도 처리된다.',
     'HARD'),

    (7,
     'Star Transformation 이 적합한 환경은?',
     'OLTP 거래 처리',
     '차원(Dimension) - 사실(Fact) 모델의 DW 환경',
     '일반적인 M:N 조인',
     '단일 테이블 풀스캔',
     2,
     'Star Transformation 은 차원-사실 스키마에서 bitmap 인덱스를 활용해 다중 차원 조건을 효율 처리한다.',
     'HARD'),

    (7,
     'PARALLEL 힌트의 일반적 효과로 옳은 것은?',
     '대용량 처리에서 CPU 자원을 더 사용해 응답시간을 단축한다',
     '항상 빠르다',
     'OLTP 의 소량 트랜잭션에 강하다',
     '디스크 사용량을 줄인다',
     1,
     '병렬 처리는 자원 투입으로 대량 처리 시간을 단축하지만, 소량 OLTP 에는 오히려 오버헤드이다.',
     'HARD'),

    (7,
     'IOT(Index-Organized Table)의 특징으로 옳은 것은?',
     '테이블 데이터가 인덱스 리프에 함께 저장된다',
     'PK 가 필요 없다',
     '항상 일반 테이블보다 빠르다',
     'NULL 만 저장 가능',
     1,
     'IOT 는 PK 기반 B-Tree 자체가 곧 테이블 데이터. PK 조회에 강하나 풀스캔은 일반 힙 테이블보다 비효율적이다.',
     'HARD');


-- ============================================================================
-- 자체 검증 노트 (적용 후 SELECT 로 확인할 것)
--
--   SELECT c.exam_type, c.name, COUNT(*) AS total,
--          SUM(CASE WHEN q.difficulty='EASY'   THEN 1 ELSE 0 END) AS easy,
--          SUM(CASE WHEN q.difficulty='MEDIUM' THEN 1 ELSE 0 END) AS medium,
--          SUM(CASE WHEN q.difficulty='HARD'   THEN 1 ELSE 0 END) AS hard
--   FROM questions q JOIN categories c ON c.id = q.category_id
--   GROUP BY c.exam_type, c.name
--   ORDER BY c.exam_type, c.id;
--
--   목표 분포 (V2 + V3 합산):
--     1 데이터 모델링의 이해 : 14 (5/7/2)   ← V2 2 + V3 12
--     2 데이터 모델과 SQL    : 15 (4/9/2)   ← V2 1 + V3 14
--     3 SQL 기본              : 18 (5/11/2) ← V2 2 + V3 16
--     4 SQL 활용              : 17 (4/10/3) ← V2 1 + V3 16
--     5 관리 구문             : 13 (4/7/2)  ← V2 1 + V3 12
--     6 SQL 수행 구조         : 16 (2/8/6)  ← V2 1 + V3 15
--     7 고급 SQL 튜닝         : 16 (1/7/8)  ← V2 1 + V3 15
--     ── 총 109문항
-- ============================================================================
